#!/bin/sh

pip install rich

sudo mkdir -p /opt/watodo/

sudo chown -R "$(whoami):$(whoami)" /opt/watodo/

chmod +x ./watodo

cp ./watodo /usr/local/bin/

cp ./watodo.py /opt/watodo/

printf "\n\nNOW YOU CAN DELETE THIS REPO\n"

exit 0