#!/bin/sh

pip install rich

sudo mkdir -p /opt/watodo/

sudo chown -R "$(whoami):$(whoami)" /opt/watodo/

chmod +x ./watodo

sudo cp ./watodo /usr/local/bin/

cp ./watodo.py /opt/watodo/

printf "\nNOW YOU CAN DELETE THIS REPO\n\n"

exit 0
